### ISSUE TITLE
Improve validation of mis placed $ref

### ISSUE THREAD

**Issue by FlatBallFlyer** [agile-learning-institute/stage0_mongodb_api#3]
$ref can only be used in place of description/type  - this is an invalid $ref placement
```yaml
type: object
properties:
  prop1:
    description: A prop
    type: object
    $ref: some_ref
```
This is proper placement
properties:
  prop1:
    $ref: some_ref
